### ISSUE TITLE
您好，D0,D1,D2 操作的引脚并没有使用啊，请问D0 D1 D2在程序中起什么作用呢

### ISSUE THREAD

**Issue by zhangyy103** [hui-shao/STM32F407_AD9851_DDS_HAL_Driver#1]

**Comment by hui-shao** [comment]
D0-D2 在串行模式下是没有使用的，所有数据都通过D7传输，此时D0-D2连接到固定电平即可，程序中也写了D0-D2的驱动，是为了考虑将其接在 IO 口上的情形，以通过程序来控制 AD9851 的行为，如果不需要控制，可以按需删除；
如果在并行模式下，会使用 D0-D7 全部端口，这些端口将全部连接到 GPIO 上，详见 Datasheet。

**Comment by zhangyy103** [comment]
谢谢大佬，还有一个问题：AD9851不能调波的幅度吗。而且一个口只能输出一种波形吗，不能让一个口输出不同的波形吗（我没有学过模电，很多都不懂，打扰您了，希望大佬能谅解）

**Comment by hui-shao** [comment]
> Author

很久没碰了，如果没记错，这东西是输出方波的，通过滤波生成正弦波。因此，不同波形应该在不同端口输出，在滤波前输出就是方波，滤波后会变成正弦波。如果是买来的模块，上面应该会有多个输出口。

**Comment by zhangyy103** [comment]
谢谢回答！
